# Generated by Django 5.1 on 2024-09-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('CSM', 'CSM'), ('CSD', 'CSD'), ('CSC', 'CSC')], max_length=10, null=True),
        ),
    ]
